# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ee96ce9a152e23b2e7396353325356d91189151463ed2d7cb8132941eea451bafad47bf21bd3a7e65b0f0e5647244e1128466a3aa9e2e86219b272832cfac23

test:
  secret_key_base: c254c9ab6b8e4f74c3fddf5a3b4bb1f6e872ae9baee398d5e3a211e451629d500f3d4cc6f5362e716c7a51efb1d160c2284edbb060836829d929f13d136ddf22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
